In [1]:
import os

In [2]:
os.chdir('../..')

In [3]:
from ogb.linkproppred import DglLinkPropPredDataset
import dgl
import torch

Using backend: pytorch


In [4]:
dataset = DglLinkPropPredDataset('ogbl-ddi', root='data/dataset_dgl')

In [5]:
graph = dataset[0]

In [6]:
graph.number_of_nodes()

4267

In [7]:
4267 ** 2

18207289

In [8]:
graph.number_of_edges()

2135822

In [9]:
graph.edges()

(tensor([4039, 2424, 4039,  ...,  338,  835, 3554]),
 tensor([2424, 4039,  225,  ...,  708, 3554,  835]))

In [10]:
graph.has_edges_between(graph.edges()[1], graph.edges()[0]).all()

tensor(True)

In [11]:
dataset.get_edge_split()

{'train': {'edge': tensor([[4039, 2424],
          [4039,  225],
          [4039, 3901],
          ...,
          [ 647,  708],
          [ 708,  338],
          [ 835, 3554]])},
 'valid': {'edge': tensor([[ 722,  548],
          [ 874, 3436],
          [ 838, 1587],
          ...,
          [3661, 3125],
          [3272, 3330],
          [1330,  776]]),
  'edge_neg': tensor([[   0,   58],
          [   0,   84],
          [   0,   90],
          ...,
          [4162, 4180],
          [4168, 4260],
          [4180, 4221]])},
 'test': {'edge': tensor([[2198, 1172],
          [1205,  719],
          [1818, 2866],
          ...,
          [ 326, 1109],
          [ 911, 1250],
          [4127, 2480]]),
  'edge_neg': tensor([[   0,    2],
          [   0,   16],
          [   0,   42],
          ...,
          [4168, 4259],
          [4208, 4245],
          [4245, 4259]])}}

In [12]:
dataset.get_edge_split()['train']['edge']

tensor([[4039, 2424],
        [4039,  225],
        [4039, 3901],
        ...,
        [ 647,  708],
        [ 708,  338],
        [ 835, 3554]])

In [13]:
train_ids = graph.edge_ids(dataset.get_edge_split()['train']['edge'][:, 0], dataset.get_edge_split()['train']['edge'][:, 1])

In [14]:
dataset.get_edge_split()['train']['edge']

tensor([[4039, 2424],
        [4039,  225],
        [4039, 3901],
        ...,
        [ 647,  708],
        [ 708,  338],
        [ 835, 3554]])

In [15]:
train_ids

tensor([      0,       2,       4,  ..., 2135816, 2135818, 2135820])

In [16]:
graph.edge_ids(4039, 225)

2

In [17]:
torch.cuda.is_available()

True

In [18]:
device = 0

In [19]:
dim = 16
walk_length = 80
window_size = 2
batch_size = 16
only_cpu = False
only_gpu = True
mix = False
neg_weight = 1.
negative = 1
lr = 0.1
lap_norm = 0.05
fast_neg = False
print_loss = True
norm = False
use_context_weight = False
async_update = False
num_threads = 16
gpus = [0]
count_params = False
num_walks = 300
num_sampler_threads = 0
print_interval = 2000
save_in_txt = False
save_in_pt = False
output_emb_file = 'deepwalk/models/01_deep_embedding.npy'

In [20]:
from deepwalk.src.deepwalk import DeepwalkTrainer

In [21]:
trainer = DeepwalkTrainer(
    graph=graph,
    device=device,
    dim=dim,
    walk_length=walk_length,
    window_size=window_size,
    batch_size=batch_size,
    only_cpu=only_cpu,
    only_gpu=only_gpu,
    mix=mix,
    neg_weight=neg_weight,
    negative=negative,
    lr=lr,
    lap_norm=lap_norm,
    fast_neg=fast_neg,
    print_loss=print_loss,
    norm=norm,
    use_context_weight=use_context_weight,
    async_update=async_update,
    num_threads=num_threads,
    gpus=gpus,
    count_params=count_params,
    num_walks=num_walks,
    num_sampler_threads=num_sampler_threads,
    print_interval=print_interval,
    save_in_txt=save_in_txt,
    save_in_pt=save_in_pt,
    output_emb_file=output_emb_file,
)

1280100 seeds in 0.03s


In [22]:
trainer.train()

Run in 1 GPU
The device is cuda:0
num batchs: 80007

Batch 2000 training time: 3.42s loss: 1.2674
Batch 4000 training time: 3.11s loss: 1.2330
Batch 6000 training time: 3.10s loss: 1.2191
Batch 8000 training time: 3.11s loss: 1.2143
Batch 10000 training time: 3.12s loss: 1.2109
Batch 12000 training time: 3.13s loss: 1.2092
Batch 14000 training time: 3.21s loss: 1.2077
Batch 16000 training time: 3.17s loss: 1.2069
Batch 18000 training time: 3.12s loss: 1.2065
Batch 20000 training time: 3.12s loss: 1.2065
Batch 22000 training time: 3.28s loss: 1.2052
Batch 24000 training time: 3.13s loss: 1.2058
Batch 26000 training time: 3.46s loss: 1.2048
Batch 28000 training time: 3.21s loss: 1.2048
Batch 30000 training time: 3.12s loss: 1.2046
Batch 32000 training time: 3.13s loss: 1.2048
Batch 34000 training time: 3.12s loss: 1.2048
Batch 36000 training time: 3.12s loss: 1.2039
Batch 38000 training time: 3.12s loss: 1.2040
Batch 40000 training time: 3.12s loss: 1.2039
Batch 42000 training time: 3.13