In [1]:
import os

In [2]:
os.chdir('../..')

In [3]:
from ogb.linkproppred import DglLinkPropPredDataset
import dgl
import torch

Using backend: pytorch


In [4]:
dataset = DglLinkPropPredDataset('ogbl-ddi', root='data/dataset_dgl')

In [5]:
graph = dataset[0]

In [6]:
graph.number_of_nodes()

4267

In [7]:
4267 ** 2

18207289

In [8]:
graph.number_of_edges()

2135822

In [9]:
graph.edges()

(tensor([4039, 2424, 4039,  ...,  338,  835, 3554]),
 tensor([2424, 4039,  225,  ...,  708, 3554,  835]))

In [10]:
graph.has_edges_between(graph.edges()[1], graph.edges()[0]).all()

tensor(True)

In [11]:
dataset.get_edge_split()

{'train': {'edge': tensor([[4039, 2424],
          [4039,  225],
          [4039, 3901],
          ...,
          [ 647,  708],
          [ 708,  338],
          [ 835, 3554]])},
 'valid': {'edge': tensor([[ 722,  548],
          [ 874, 3436],
          [ 838, 1587],
          ...,
          [3661, 3125],
          [3272, 3330],
          [1330,  776]]),
  'edge_neg': tensor([[   0,   58],
          [   0,   84],
          [   0,   90],
          ...,
          [4162, 4180],
          [4168, 4260],
          [4180, 4221]])},
 'test': {'edge': tensor([[2198, 1172],
          [1205,  719],
          [1818, 2866],
          ...,
          [ 326, 1109],
          [ 911, 1250],
          [4127, 2480]]),
  'edge_neg': tensor([[   0,    2],
          [   0,   16],
          [   0,   42],
          ...,
          [4168, 4259],
          [4208, 4245],
          [4245, 4259]])}}

In [12]:
dataset.get_edge_split()['train']['edge']

tensor([[4039, 2424],
        [4039,  225],
        [4039, 3901],
        ...,
        [ 647,  708],
        [ 708,  338],
        [ 835, 3554]])

In [13]:
train_ids = graph.edge_ids(dataset.get_edge_split()['train']['edge'][:, 0], dataset.get_edge_split()['train']['edge'][:, 1])

In [14]:
dataset.get_edge_split()['train']['edge']

tensor([[4039, 2424],
        [4039,  225],
        [4039, 3901],
        ...,
        [ 647,  708],
        [ 708,  338],
        [ 835, 3554]])

In [15]:
train_ids

tensor([      0,       2,       4,  ..., 2135816, 2135818, 2135820])

In [16]:
graph.edge_ids(4039, 225)

2

In [17]:
torch.cuda.is_available()

True

In [18]:
device = 0

In [19]:
dim = 16
walk_length = 5
window_size = 5
batch_size = 1000
only_cpu = True
only_gpu = False
mix = False
neg_weight = 1.
negative = 1
lr = 0.01
lap_norm = 0.01
fast_neg = False
print_loss = True
norm = False
use_context_weight = False
async_update = False
num_threads = 16
gpus = [-1]
count_params = False
num_walks = 10000
num_sampler_threads = 0
print_interval = 1000
save_in_txt = False
save_in_pt = False
output_emb_file = 'deepwalk/models/01_deep_embedding.npy'

In [20]:
from deepwalk.src.deepwalk import DeepwalkTrainer

In [21]:
trainer = DeepwalkTrainer(
    graph=graph,
    device=device,
    dim=dim,
    walk_length=walk_length,
    window_size=window_size,
    batch_size=batch_size,
    only_cpu=only_cpu,
    only_gpu=only_gpu,
    mix=mix,
    neg_weight=neg_weight,
    negative=negative,
    lr=lr,
    lap_norm=lap_norm,
    fast_neg=fast_neg,
    print_loss=print_loss,
    norm=norm,
    use_context_weight=use_context_weight,
    async_update=async_update,
    num_threads=num_threads,
    gpus=gpus,
    count_params=count_params,
    num_walks=num_walks,
    num_sampler_threads=num_sampler_threads,
    print_interval=print_interval,
    save_in_txt=save_in_txt,
    save_in_pt=save_in_pt,
    output_emb_file=output_emb_file,
)

42670000 seeds in 2.23s


In [22]:
trainer.train()

Run in CPU process
num batchs: 42670

Batch 1000 training time: 18.39s loss: 1.3099
Batch 2000 training time: 14.93s loss: 1.2680
Batch 3000 training time: 15.03s loss: 1.2537
Batch 4000 training time: 14.97s loss: 1.2454
Batch 5000 training time: 14.95s loss: 1.2395
Batch 6000 training time: 14.92s loss: 1.2350
Batch 7000 training time: 14.94s loss: 1.2316
Batch 8000 training time: 14.93s loss: 1.2283
Batch 9000 training time: 15.01s loss: 1.2263
Batch 10000 training time: 14.91s loss: 1.2247
Batch 11000 training time: 15.03s loss: 1.2225
Batch 12000 training time: 15.05s loss: 1.2205
Batch 13000 training time: 15.01s loss: 1.2199
Batch 14000 training time: 15.01s loss: 1.2185
Batch 15000 training time: 14.93s loss: 1.2172
Batch 16000 training time: 14.88s loss: 1.2163
Batch 17000 training time: 14.89s loss: 1.2144
Batch 18000 training time: 14.89s loss: 1.2144
Batch 19000 training time: 14.89s loss: 1.2136
Batch 20000 training time: 14.89s loss: 1.2122
Batch 21000 training time: 14.8